extends:
  # Airbnb rules
  - airbnb
  # Idiomatic for layout only
  - idiomatic/core
env:
  node: true
rules:
  no-console: off
  func-names: off
  comma-dangle:
    - error
    - always-multiline
  semi:
    - error
    - always
  one-var:
    - error
    -
      initialized: never
      uninitialized: always
  camelcase: off
  consistent-return: warn
